---
- name: create {{ usenet_incomplete_download_directory }}
  file:
    path: "{{ usenet_incomplete_download_directory }}"
    state: directory
    mode: 0755
    owner: "{{ media_user_uid }}"
    group: "{{ media_user_gid }}"

- name: create {{ usenet_complete_download_directory }}
  file:
    path: "{{ usenet_complete_download_directory }}/{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ media_user_uid }}"
    group: "{{ media_user_gid }}"
  with_items:
    - tv
    - movies
    - software
    - music
