---
- name: Generate Plex InfluxDB Collector config file
  template:
    src: plex-influx-config.ini.j2
    dest: '{{ media_root }}/configs/plex-influxdb-collector/config.ini'
  notify: restart plex-influxdb-collector