---
- name: Generate Plex InfluxDB config file
  template:
    src: plex-influx-config.ini.j2
    dest: '{{ media_root }}/configs/plex-influxdb-collector/config.ini'

- name: Copy image to host
  copy:
    src: /tmp/plex-influx.tar
    dest: /tmp/plex-influx.tar

- name: Load docker image
  docker_image:
    name: plex-influx
    load_path: /tmp/plex-influx.tar

- name: Start Plex InfluxDB Stats Collector
  docker_container:
    name: plex-influx
    image: plex-influx
    volumes:
      - '{{ media_root }}/configs/plex-influxdb-collector:/plex-influxdb-collector'
    state: 'started'
    restart_policy: 'always'
    log_driver: 'syslog'
    log_options:
      tag: "plex-influx"
