---
# Install docker-py for image building
- name: Install docker-py module for image building
  pip:
    name: docker-py
    state: present
    
# Check out plex influx collector source
- name: Check out Plex InfluxDB Collector Repository
  git:
    repo: 'https://github.com/ajanis/Plex-to-InfluxDB-Extended.git'
    dest: /tmp/plex-influx

# Build docker image    
- name: Build Plex InfluxDB Collector Image
  docker_image:
     path: /tmp/plex-influx
     name: plex-influx

# Create influx collector config file
- name: Generate Plex InfluxDB config file
  template:
    src: plex-influx-config.ini.j2
    dest: '{{ media_root }}/configs/plex-influxdb-collector/config.ini'
  notify: restart plex-influxdb-collector

# Import Docker role to create media service containers and startup files
- name: Set up Docker containers
  import_role:
    name: docker
    tasks_from: container-setup

- name: Create Docker Container Systemd Services
  import_role:
    name: docker
    tasks_from: container-service