---
- name: Check out Plex InfluxDB Collector Repository
  git:
    repo: 'https://github.com/ajanis/Plex-to-InfluxDB-Extended.git'
    dest: /tmp/plex-influx
- name: Build Plex InfluxDB Collector Image
  docker_image:
     path: /tmp/plex-influx
     name: plex-influx
- name: Save image to archive
  docker_image:
    name: plex-influx
    archive_path: /tmp/plex-influx.tar
- name: Generate Plex InfluxDB config file
  template:
    src: plex-influx-config.ini.j2
    dest: '{{ media_root }}/configs/plex-influxdb-collector/config.ini'
  notify: restart plex-influxdb-collector
- name: Load docker image
docker_image:
  name: plex-influx
  load_path: /tmp/plex-influx.tar
notify: restart plex-influxdb-collector
# Import Docker role to create media service containers and startup files
- name: Set up Docker containers
  import_role:
    name: docker
    tasks_from: container-setup

- name: Create Docker Container Systemd Services
  import_role:
    name: docker
    tasks_from: container-service