---
- name: install apache2
  apt:
    name: apache2
    update_cache: yes
    state: present

- name: create public_html directory
  file:
    path: "{{ data_mount_root }}/{{ www_directory }}"
    state: directory
    mode: 0755
    owner: 2000
    group: 2000
  notify:
    - restart apache2

- name: Install SSL Key
  copy:
    content: "{{ item.sslkeycontent }}"
    dest: "{{ item.sslkeyfile }}"
    owner: root
    group: ssl-cert
    mode: 0640
  with_items: "{{ apache_vhosts_ssl }}"
  notify:
    - restart apache2

- name: Install SSL Certificate Chain
  copy:
    content: "{{ item.sslcertcontent }}"
    dest: "{{ item.sslcertfile }}"
    owner: root
    group: ssl-cert
    mode: 0640
  with_items: "{{ apache_vhosts_ssl }}"
  notify:
    - restart apache2

- name: install apache modules
  apt:
    update_cache: yes
    state: present
    name:
      - libapache2-mod-php7.2
      - libapache2-mod-security2
      - libapache2-mod-evasive

- name: enable apache modules
  apache2_module:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.2
    - ssl
    - rewrite
    - proxy
    - proxy_html
    - proxy_http
    - status
    - security2
    - evasive
    - headers
  notify:
    - restart apache2


- name: add additional listen ports
  blockinfile:
    path: /etc/apache2/ports.conf
    block: |
      Listen 8080
      <IfModule ssl_module>
          Listen 8443
      </IfModule>
      <IfModule mod_gnutls.c>
          Listen 8443
      </IfModule>
    state: present
  notify:
    - restart apache2

- name: Update apache run-as user to media
  replace:
    path: /etc/apache2/envvars
    regexp: '^exp.*APACHE_RUN_USER.*'
    replace: 'export APACHE_RUN_USER=media'

- name: Update apache run-as group to media
  replace:
    path: /etc/apache2/envvars
    regexp: '^exp.*APACHE_RUN_GROUP.*'
    replace: 'export APACHE_RUN_GROUP=media'

- name: Update apache security config
  template:
    src: security.conf.j2
    dest: /etc/apache2/conf-available/security.conf
    owner: root
  notify:
    - restart apache2

- name: Update mod_evasive config
  template:
    src: evasive.conf.j2
    dest: /etc/apache2/mods-available/evasive.conf
    owner: root
  notify:
    - restart apache2

- name: Install apache mod_security config
  copy:
    src: modsecurity.conf
    dest: /etc/modsecurity/modsecurity.conf
    owner: root
  notify:
    - restart apache2

- name: default site
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
    owner: root
  notify:
    - restart apache2

- name: a2ensite 000-default
  command: a2ensite 000-default
  args:
    creates: /etc/apache2/sites-enabled/000-default.conf
  notify:
    - restart apache2

- name: default ssl site
  template:
    src: 001-default-ssl.conf.j2
    dest: /etc/apache2/sites-available/001-default-ssl.conf
    owner: root
  notify:
    - restart apache2

- name: a2ensite 001-default-ssl
  command: a2ensite 001-default-ssl
  args:
    creates: /etc/apache2/sites-enabled/001-default-ssl.conf
  notify:
    - restart apache2

- name: apache2 service
  service:
    name: apache2
    state: started
