- name: restart avahi-daemon
  service:
    name: avahi-daemon
    state: restarted

- name: restart netatalk
  service:
    name: netatalk
    state: restarted

- name: restart samba
  service:
    name: smbd
    state: restarted

- name: restart apache2
  service:
    name: apache2
    state: restarted