---
- name: install netatalk
  apt: 
    name: netatalk 
    update_cache: yes
    state: latest

- name: install avahi-daemon
  apt: 
    name: avahi-daemon 
    update_cache: yes 
    state: latest

- name: install samba server
  apt: 
    name: samba 
    update_cache: yes 
    state: latest

- name: samba defaults
  copy: 
    src: smb.conf 
    dest: /etc/samba/smb.conf
  notify:
    - restart samba

- name: install libnss-mdns
  apt: 
    name: libnss-mdns 
    update_cache: yes 
    state: latest

- name: netatalk defaults
  copy: 
    src: netatalk 
    dest: /etc/default/netatalk
  notify:
    - restart netatalk

- name: netatalk shares
  copy: 
    src: AppleVolumes.default 
    dest: /etc/netatalk/AppleVolumes.default
  notify:
    - restart netatalk

- name: nsswitch config
  lineinfile: 
    dest: /etc/nsswitch.conf 
    regexp: '^hosts:' 
    line: 'hosts: files mdns4_minimal dns mdns4 mdns'
  notify:
    - restart netatalk

- name: afp model
  lineinfile: 
    dest: /etc/netatalk/afpd.conf 
    line: '-mimicmodel Xserve'
  notify:
    - restart netatalk

- name: afp ldap config
  template:
    src: afp_ldap.conf.j2
    dest: /etc/netatalk/afp_ldap.conf
  notify:
    - restart avahi-daemon
    - restart netatalk
  when: afp_ldap_auth | default('False')
    
- name: afpd service
  copy: 
    src: afpd.service 
    dest: /etc/avahi/services/afpd.service
  notify:
    - restart avahi-daemon

- name: netatalk service
  service: 
    name: netatalk 
    state: started

- name: avahi-daemon service
  service: 
    name: avahi-daemon 
    state: started

- name: samba service
  service: 
    name: smbd 
    state: started
